import {
  FacultyFeedbackItem,
  FeedbackQuestion,
} from "@/src/features/feedback/api/feedback";

/**
 * Demo faculty list for feedback
 */
export const DEMO_FACULTY_LIST: FacultyFeedbackItem[] = [
  {
    session_id: 18,
    batch_id: 2025,
    sem_id: 1,
    course_id: 2,
    stream_id: 20,
    sub_id: 12469,
    sub_code: "R25_M101",
    sub_name: "ENGINEERING MATHEMATICS",
    sec_id: 1,
    sec_name: "SEC-I",
    fac_code: "DEMO/F001",
    fac_sht_name: "AK",
    fac_name: "Amit Kumar",
    sub_type: 1,
    app: "Click Here - SEC-I",
    pending: 0,
    done: 0,
    fac_image: "",
    totalRating: 0,
  },
  {
    session_id: 18,
    batch_id: 2025,
    sem_id: 1,
    course_id: 2,
    stream_id: 20,
    sub_id: 12471,
    sub_code: "R25_PH101",
    sub_name: "ENGINEERING PHYSICS",
    sec_id: 1,
    sec_name: "SEC-I",
    fac_code: "DEMO/F002",
    fac_sht_name: "RS",
    fac_name: "Rahul Sen",
    sub_type: 1,
    app: "Click Here - SEC-I",
    pending: 0,
    done: 0,
    fac_image: "",
    totalRating: 100,
  },
  {
    session_id: 18,
    batch_id: 2025,
    sem_id: 1,
    course_id: 2,
    stream_id: 20,
    sub_id: 12486,
    sub_code: "R25_PH191",
    sub_name: "ENGINEERING PHYSICS LAB",
    sec_id: 1,
    sec_name: "SEC-I",
    fac_code: "DEMO/F003",
    fac_sht_name: "NM",
    fac_name: "Neha Malhotra",
    sub_type: 0,
    app: "Click Here - SEC-I",
    pending: 0,
    done: 0,
    fac_image: "",
    totalRating: 100,
  },
  {
    session_id: 18,
    batch_id: 2025,
    sem_id: 1,
    course_id: 2,
    stream_id: 20,
    sub_id: 12477,
    sub_code: "R25_CS191",
    sub_name: "INTRODUCTION TO PROGRAMMING AND PROBLEM-SOLVING LAB",
    sec_id: 1,
    sec_name: "SEC-I",
    fac_code: "DEMO/F004",
    fac_sht_name: "AP",
    fac_name: "Ankit Patel",
    sub_type: 0,
    app: "Click Here - SEC-I",
    pending: 0,
    done: 0,
    fac_image: "",
    totalRating: 0,
  },
  {
    session_id: 18,
    batch_id: 2025,
    sem_id: 1,
    course_id: 2,
    stream_id: 20,
    sub_id: 12482,
    sub_code: "R25_HU191",
    sub_name: "COMMUNICATION AND PRESENTATION SKILL",
    sec_id: 1,
    sec_name: "SEC-I",
    fac_code: "DEMO/F005",
    fac_sht_name: "PS",
    fac_name: "Priya Sharma",
    sub_type: 0,
    app: "Click Here - SEC-I",
    pending: 0,
    done: 0,
    fac_image: "",
    totalRating: -10,
  },
  {
    session_id: 18,
    batch_id: 2025,
    sem_id: 1,
    course_id: 2,
    stream_id: 20,
    sub_id: 12460,
    sub_code: "R25_CS101",
    sub_name: "INTRODUCTION TO PROGRAMMING AND PROBLEM SOLVING",
    sec_id: 1,
    sec_name: "SEC-I",
    fac_code: "DEMO/F006",
    fac_sht_name: "VK",
    fac_name: "Vikas Khanna",
    sub_type: 1,
    app: "Click Here - SEC-I",
    pending: 0,
    done: 0,
    fac_image: "",
    totalRating: 0,
  },
  {
    session_id: 18,
    batch_id: 2025,
    sem_id: 1,
    course_id: 2,
    stream_id: 20,
    sub_id: 12465,
    sub_code: "R25_HU101",
    sub_name: "ENVIRONMENTAL SCIENCE",
    sec_id: 1,
    sec_name: "SEC-I",
    fac_code: "DEMO/F007",
    fac_sht_name: "SM",
    fac_name: "Sneha Mehta",
    sub_type: 1,
    app: "Click Here - SEC-I",
    pending: 0,
    done: 0,
    fac_image: "",
    totalRating: 100,
  },
];

/**
 * Demo feedback questions for a faculty
 */
export function getDemoFeedbackQuestions(): FeedbackQuestion[] {
  return [
    {
      id: 1,
      prefix: "A",
      head: "1. COURSE COVERAGE",
      subhead: "Completion of course as per lesson plan",
      rating: 1,
    },
    {
      id: 2,
      prefix: "B",
      head: "2. PRESENTATION SKILL",
      subhead: "Communication clarity, body language, and use of teaching aids",
      rating: 1,
    },
    {
      id: 3,
      prefix: "C",
      head: "3. REGULARITY & PUNCTUALITY",
      subhead: "Maintaining class schedule and timely sessions",
      rating: 1,
    },
    {
      id: 4,
      prefix: "D",
      head: "4. INTERACTIVE TEACHING METHODOLOGY",
      subhead: "Encouragement of questions and participative learning",
      rating: 1,
    },
    {
      id: 5,
      prefix: "E",
      head: "5. CREATIVE / INNOVATIVE LEARNING",
      subhead: "Use of innovative methods to explain concepts",
      rating: 1,
    },
    {
      id: 6,
      prefix: "F",
      head: "6. STUDENT SATISFACTION",
      subhead: "Clarity of concepts and learning satisfaction",
      rating: 1,
    },
    {
      id: 7,
      prefix: "G",
      head: "7. APPROACHABILITY",
      subhead: "Availability and willingness to help students",
      rating: 1,
    },
    {
      id: 8,
      prefix: "H",
      head: "8. QUERY HANDLING",
      subhead: "Effectiveness in answering questions and doubts",
      rating: 1,
    },
    {
      id: 9,
      prefix: "I",
      head: "9. ASSESSMENT",
      subhead: "Fairness and transparency in evaluation",
      rating: 1,
    },
    {
      id: 10,
      prefix: "J",
      head: "10. BEYOND CURRICULUM",
      subhead: "Teaching beyond syllabus and practical exposure",
      rating: 1,
    },
  ];
}
