import {
  LibraryBook,
  LibrarySearchResult,
} from "@/src/features/library/types";
import { DEMO_STUDENT } from "./constants";

/**
 * Create mock library books data for demo mode.
 */
export function getDemoLibraryBooks(): LibraryBook[] {
  return [
    {
      acc_type_id: 100,
      acc_type: "Book Bank",
      reader_id: DEMO_STUDENT.id,
      reader_code: DEMO_STUDENT.code,
      reader_name: DEMO_STUDENT.name,
      reader_dept: DEMO_STUDENT.batch,
      reader_acc_id: 10001,
      reader_acc_no: "BB00001",
      reader_acc_name: "Let Us C",
      issue_date: "14/10/2025",
      return_date: "31/12/2025",
      return_id: 0,
    },
    {
      acc_type_id: 100,
      acc_type: "Book Bank",
      reader_id: DEMO_STUDENT.id,
      reader_code: DEMO_STUDENT.code,
      reader_name: DEMO_STUDENT.name,
      reader_dept: DEMO_STUDENT.batch,
      reader_acc_id: 10002,
      reader_acc_no: "BB00002",
      reader_acc_name: "Basic Environmental Engineering and Elementary Biology",
      issue_date: "14/10/2025",
      return_date: "31/12/2025",
      return_id: 0,
    },
    {
      acc_type_id: 100,
      acc_type: "Book Bank",
      reader_id: DEMO_STUDENT.id,
      reader_code: DEMO_STUDENT.code,
      reader_name: DEMO_STUDENT.name,
      reader_dept: DEMO_STUDENT.batch,
      reader_acc_id: 10003,
      reader_acc_no: "BB00003",
      reader_acc_name:
        "Engineering Mathematics Volume - I: For 1st Year 1st Semester Courses of All the Streams",
      issue_date: "14/10/2025",
      return_date: "31/12/2025",
      return_id: 0,
    },
    {
      acc_type_id: 100,
      acc_type: "Book Bank",
      reader_id: DEMO_STUDENT.id,
      reader_code: DEMO_STUDENT.code,
      reader_name: DEMO_STUDENT.name,
      reader_dept: DEMO_STUDENT.batch,
      reader_acc_id: 10004,
      reader_acc_no: "BB00004",
      reader_acc_name:
        "Modern Engineering Physics: For the Students of B.E. / B. Tech. of All Technical Universities of India",
      issue_date: "14/10/2025",
      return_date: "31/12/2025",
      return_id: 0,
    },
  ];
}

/**
 * Create mock library search results for demo mode.
 */
export function getDemoLibrarySearchResults(): LibrarySearchResult[] {
  return [
    {
      sl_no: 22,
      acc_title: "Head first Java",
      acc_edition: "",
      acc_author: "Sierra, Kathy",
      acc_subject: "",
      tot_copy: 1,
      tot_shelf: 1,
      tot_issued: 0,
      tot_ref_book: 1,
      m_sel: "Sel",
      m_book: "Book",
    },
    {
      sl_no: 26,
      acc_title: "Java 2: the complete reference",
      acc_edition: "",
      acc_author: "Schildt, Herbert",
      acc_subject: "",
      tot_copy: 116,
      tot_shelf: 87,
      tot_issued: 29,
      tot_ref_book: 0,
      m_sel: "Sel",
      m_book: "Book",
    },
    {
      sl_no: 33,
      acc_title: "Java examples in a nutshell",
      acc_edition: "3rd ed",
      acc_author: "Flanagan, David",
      acc_subject: "",
      tot_copy: 3,
      tot_shelf: 3,
      tot_issued: 0,
      tot_ref_book: 2,
      m_sel: "Sel",
      m_book: "Book",
    },
    {
      sl_no: 39,
      acc_title: "Java script: the definitive guide",
      acc_edition: "",
      acc_author: "Flanagan, David",
      acc_subject: "",
      tot_copy: 10,
      tot_shelf: 10,
      tot_issued: 0,
      tot_ref_book: 2,
      m_sel: "Sel",
      m_book: "Book",
    },
    {
      sl_no: 45,
      acc_title: "Java threads",
      acc_edition: "2nd ed",
      acc_author: "Oaks, Scott",
      acc_subject: "",
      tot_copy: 10,
      tot_shelf: 10,
      tot_issued: 0,
      tot_ref_book: 2,
      m_sel: "Sel",
      m_book: "Book",
    },
    {
      sl_no: 54,
      acc_title: "Murach's JavaScript and dom scripting",
      acc_edition: "",
      acc_author: "Harris, Ray",
      acc_subject: "",
      tot_copy: 5,
      tot_shelf: 4,
      tot_issued: 1,
      tot_ref_book: 2,
      m_sel: "Sel",
      m_book: "Book",
    },
    {
      sl_no: 64,
      acc_title: "Operating system concepts with JAVA",
      acc_edition: "6th",
      acc_author: "Silberschatz, Abraham",
      acc_subject: "",
      tot_copy: 110,
      tot_shelf: 104,
      tot_issued: 6,
      tot_ref_book: 0,
      m_sel: "Sel",
      m_book: "Book",
    },
    {
      sl_no: 77,
      acc_title: "Sams Teach Yourself HTML, CSS, and JavaScript All in One",
      acc_edition: "3rd ed",
      acc_author: "Jennifer Kyrnin, Julie Meloni",
      acc_subject: "",
      tot_copy: 20,
      tot_shelf: 20,
      tot_issued: 0,
      tot_ref_book: 0,
      m_sel: "Sel",
      m_book: "Book",
    },
  ];
}
